apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Jupiter
  annotations:
    github.com/project-slug: gabrielbuzziv/backstage-poc
spec:
  type: other
  lifecycle: unknown
  owner: Discover
